import type { Metadata } from "next";
import "../style/globals.css";
import localFont from "next/font/local";
import Providers from "@/store/Providers";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/common/Footer";

const iranSans = localFont({
  src: "../../public/fonts/IRANSans.ttf",
  variable: "--font-iran-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html dir="rtl" lang="fa">
      <body className={`${iranSans.variable} antialiased bg-dark-blue  overflow-x-hidden `}>
        <Providers>
          <Navbar />
          <main className="mt-32 w-full md:px-0" >
            {children}
          </main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
